version: '3.8'
services:
  redis_server:
    container_name: redis_server
    image: 'redislabs/redismod'
    volumes:
      - redis_data:/data
    ports: # enable to visualize data in redis insight
      - '6379:6379'

  mongodb_server:
    container_name: mongodb_server
    image: 'mongo'
    volumes:
      - mongodb_data:/data/db
    ports: # enable to visualize data in mongodb compass
      - '27017:27017'

volumes:
  redis_data:
  mongodb_data:
